language: node_js
node_js:
  - "0.11"
before_install:
- export DISPLAY=:99.0
- npm install -qg bower gulp
- npm install -q
- bower install --force
before_script:
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
